### ISSUE TITLE
ROSConDemo Manipulator/MotorizedJointBus.h file not found

### ISSUE THREAD

**Issue by arturkamieniecki** [o3de/ROSConDemo#247]
After changes introduced in https://github.com/o3de/o3de-extras/pull/253, ROSConDemo project no longer compiles. The error message show is 
```
/home/artur/O3DE/Projects/ROSConDemo/Project/Gem/Source/Manipulator/KrakenManipulatorController.cpp:10:10: fatal error: 'ROS2/Manipulator/MotorizedJointBus.h' file not found
#include <ROS2/Manipulator/MotorizedJointBus.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by arturkamieniecki** [comment]
Will be resolved with #239.
